In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
df=pd.read_csv("data.csv")
df.head()

,valence,year,acousticness,artists,danceability,duration_ms,energy,explicit,id,instrumentalness,key,liveness,loudness,mode,name,popularity,release_date,speechiness,tempo
0,0.0594,1921,0.982,"['Sergei Rachmaninoff', 'James Levine', 'Berli...",0.279,831667,0.211,0,4BJqT0PrAfrxzMOxytFOIz,0.878000,10,0.665,-20.096,1,"Piano Concerto No. 3 in D Minor, Op. 30: III. ...",4,1921,0.0366,80.954
1,0.9630,1921,0.732,['Dennis Day'],0.819,180533,0.341,0,7xPhfUan2yNtyFG0cUWkt8,0.000000,7,0.160,-12.441,1,Clancy Lowered the Boom,5,1921,0.4150,60.936
2,0.0394,1921,0.961,['KHP Kridhamardawa Karaton Ngayogyakarta Hadi...,0.328,500062,0.166,0,1o6I8BglA6ylDMrIELygv1,0.913000,3,0.101,-14.850,1,Gati Bali,5,1921,0.0339,110.339
3,0.1650,1921,0.967,['Frank Parker'],0.275,210000,0.309,0,3ftBPsC5vPBKxYSee08FDH,0.000028,5,0.381,-9.316,1,Danny Boy,3,1921,0.0354,100.109
4,0.2530,1921,0.957,['Phil Regan'],0.418,166693,0.193,0,4d6HGyGT8e121BsdKmw9v6,0.000002,3,0.229,-10.096,1,When Irish Eyes Are Smiling,2,1921,0.0380,101.665

In [6]:
# null values
pd.isnull(df).sum()

valence             0
year                0
acousticness        0
artists             0
danceability        0
duration_ms         0
energy              0
explicit            0
id                  0
instrumentalness    0
key                 0
liveness            0
loudness            0
mode                0
name                0
popularity          0
release_date        0
speechiness         0
tempo               0
dtype: int64

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 170653 entries, 0 to 170652
Data columns (total 19 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   valence           170653 non-null  float64
 1   year              170653 non-null  int64
 2   acousticness      170653 non-null  float64
 3   artists           170653 non-null  str
 4   danceability      170653 non-null  float64
 5   duration_ms       170653 non-null  int64
 6   energy            170653 non-null  float64
 7   explicit          170653 non-null  int64
 8   id                170653 non-null  str
 9   instrumentalness  170653 non-null  float64
 10  key               170653 non-null  int64
 11  liveness          170653 non-null  float64
 12  loudness          170653 non-null  float64
 13  mode              170653 non-null  int64
 14  name              170653 non-null  str
 15  popularity        170653 non-null  int64
 16  release_date      170653 non-null  str
 17  speechiness       170653 non-null  float64
 18  tempo             170653 non-null  float64
dtypes: float64(9), int64(6), str(4)
memory usage: 24.7 MB

In [8]:
sorted_df=df.sort_values('popularity',ascending = True).head(5)
sorted_df

,valence,year,acousticness,artists,danceability,duration_ms,energy,explicit,id,instrumentalness,key,liveness,loudness,mode,name,popularity,release_date,speechiness,tempo
21,0.2400,1921,0.994,"['John McCormack', 'Edwin Schneider']",0.400,187333,0.1550,0,0RPKAq5yhbom6hXQz5qo6L,0.000043,4,0.1030,-13.976,1,Mother Machree,0,1921,0.0873,170.251
20,0.6720,1921,0.994,['Fortugé'],0.670,191333,0.1130,0,0QvUUTHYUQQhSXLwffzjL7,0.000000,10,0.2130,-16.570,0,Je Suis Toujours La,0,1921,0.1960,87.162
19,0.5270,1921,0.971,['Christopher Lynch'],0.540,122000,0.0848,0,0QU5xT6Mik4vpyt1ItsRXK,0.001960,5,0.0887,-16.055,0,A Ballynure Ballad,0,1921,0.0750,100.296
18,0.0778,1921,0.148,['THE GUY'],0.604,204957,0.4180,1,0QQmUf4aPFaN9U2yRko595,0.038200,4,0.1020,-11.566,0,When We Die,0,1921-09-11,0.0417,80.073
17,0.6640,1921,0.996,"['Hector Berlioz', 'Arturo Toscanini']",0.541,250747,0.2830,0,0POO8XaUgW5Qjbv9sbDy8W,0.898000,9,0.3930,-14.808,1,Rákóczy March,0,1921,0.0477,108.986

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df.to_csv("spotify_data_cleaned.csv")

In [11]:
df=pd.read_csv("spotify_data_cleaned.csv")